# -*- coding: utf-8 -*-
# @Time    : 2025/7/22 下午1:13
# @Author  : liguochun
# @FileName: train.py
# @Software: PyCharm
# @Email   ：liguochun0304@163.com
import json
import os
import random
from datetime import datetime

import numpy as np
import torch

from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from torchvision import transforms
from tqdm import tqdm
from transformers import get_linear_schedule_with_warmup

from dataloader import MMPNERDataset, MMPNERProcessor, collate_fn
from model import build_model
from test import evaluate_model
from test import load_config

script_dir = os.path.dirname(os.path.abspath(__file__))


def set_seed(seed=42):
    random.seed(seed)  # Python 随机种子
    np.random.seed(seed)  # numpy 随机种子
    torch.manual_seed(seed)  # CPU torch 随机种子
    torch.cuda.manual_seed(seed)  # GPU 随机种子
    torch.cuda.manual_seed_all(seed)  # 多 GPU 情况

    # 保证 CUDA 可复现（但可能会略微降低速度）
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    os.environ['PYTHONHASHSEED'] = str(seed)


def save_model_checkpoint(model, optimizer, scheduler, config, save_dir, epoch, best_metric):
    os.makedirs(save_dir, exist_ok=True)

    torch.save(model.state_dict(), os.path.join(save_dir, "model.pt"))
    torch.save(optimizer.state_dict(), os.path.join(save_dir, "optimizer.pt"))
    torch.save(scheduler.state_dict(), os.path.join(save_dir, "scheduler.pt"))

    with open(os.path.join(save_dir, "config.json"), "w") as f:
        json.dump(vars(config), f, indent=2)

    with open(os.path.join(save_dir, "training_state.json"), "w") as f:
        json.dump({"epoch": epoch, "best_f1": best_metric}, f, indent=2)


def load_model_checkpoint(model, optimizer, scheduler, load_dir):
    model.load_state_dict(torch.load(os.path.join(load_dir, "model.pt")))
    optimizer.load_state_dict(torch.load(os.path.join(load_dir, "optimizer.pt")))
    scheduler.load_state_dict(torch.load(os.path.join(load_dir, "scheduler.pt")))

    with open(os.path.join(load_dir, "training_state.json")) as f:
        state = json.load(f)

    return state["epoch"], state["best_f1"]


def train(config):
    print("train config:", config)
    run_name = "{0}_train-{1}_{2}_{3}".format(datetime.now().strftime('%Y-%m-%d'), config.dataset_name, str(config.model), config.ex_name)
    save_dir = os.path.join(script_dir, "save_models", "{0}".format(run_name))
    tb_dir = os.path.join("/root/tf-logs", run_name)
    os.makedirs(tb_dir, exist_ok=True)
    writer = SummaryWriter(log_dir=tb_dir)

    device = torch.device(config.device)

    DATA_PATH = {
        "twitter2015": {
            # text data
            'train': os.path.join(script_dir, 'data/twitter2015/train.txt'),
            'valid': os.path.join(script_dir, 'data/twitter2015/valid.txt'),
            'test': os.path.join(script_dir, 'data/twitter2015/test.txt'),
        },
        "twitter2017": {
            # text data
            'train': os.path.join(script_dir, 'data/twitter2017/train.txt'),
            'valid': os.path.join(script_dir, 'data/twitter2017/valid.txt'),
            'test': os.path.join(script_dir, 'data/twitter2017/test.txt'),
        },
        "NewsMKG": {
            # text data generated by processor for NewsMKG
            'train': os.path.join(script_dir, 'data/NewsMKG/train.txt'),
            'valid': os.path.join(script_dir, 'data/NewsMKG/valid.txt'),
            'test': os.path.join(script_dir, 'data/NewsMKG/test.txt'),
        }
    }
    # image data
    IMG_PATH = {
        'twitter2015': os.path.join(script_dir, 'data/twitter2015/twitter2015_images'),
        'twitter2017': os.path.join(script_dir, 'data/twitter2017/twitter2017_images'),
        # 对 NewsMKG，IMGID 已含 samples/xxx/yyy，追加 .jpg 时使用此前缀
        'NewsMKG': os.path.join(script_dir, 'data/NewsMKG'),
    }
    img_path = IMG_PATH[config.dataset_name]
    data_path = DATA_PATH[config.dataset_name]
    transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])])
    processor = MMPNERProcessor(data_path, config.text_encoder)
    train_dataset = MMPNERDataset(
        processor, transform, img_path=img_path, max_seq=config.max_len,
        sample_ratio=1.0, mode='train'
    )
    train_loader = DataLoader(
        train_dataset, batch_size=64, shuffle=True,
        num_workers=0,       # 避免多进程占用 /dev/shm
        pin_memory=False,    # 关闭 pinned 内存以减轻内存压力
        collate_fn=collate_fn
    )

    val_dataset = MMPNERDataset(
        processor,
        transform,
        img_path=img_path,
        max_seq=config.max_len,
        sample_ratio=1.0,
        mode='valid'
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=config.batch_size,
        shuffle=False,  # 验证集不打乱
        num_workers=0,       # 避免多进程占用 /dev/shm
        pin_memory=False,
        collate_fn=collate_fn
    )

    config.num_labels = len(train_dataset.label_mapping)

    start_epoch = 0
    best_f1 = 0.0
    if config.continue_train_name == "None":
        # 正常首次训练
        model = build_model(config).to(device)
    else:
        SAVE_ROOT = os.path.join(script_dir, "save_models")
        # 从 save_models/<name> 读取先前 config 以确保结构一致
        ckpt_dir = os.path.join(SAVE_ROOT, config.continue_train_name)
        prev_cfg = load_config(config.continue_train_name)  # 你已有的函数

        # 用先前配置构建结构，但运行参数沿用当前命令行（比如新的 LR/drop/align 等）
        model = build_model(prev_cfg).to(device)

    no_decay = ["bias", "LayerNorm.weight", "LayerNorm.bias"]

    # ---- 互斥划分参数：确保同一个 tensor 只落在一个组里 ----
    param_roberta, param_clip, param_downstream = [], [], []
    for n, p in model.named_parameters():
        if n.startswith("text_encoder."):
            param_roberta.append((n, p))
        elif n.startswith("clip_vision.") or n.startswith("clip.vision_model."):
            # 兼容两种命名：你自己模块里的 clip_vision.*，以及 transformers 的 clip.vision_model.*
            param_clip.append((n, p))
        else:
            param_downstream.append((n, p))

    # 小工具：给某一类(named params)按有/无weight_decay切分，跳过不需要训练的参数
    def build_groups(named_params, lr, wd):
        params_decay = [p for n, p in named_params
                        if p.requires_grad and not any(nd in n for nd in no_decay)]
        params_nodec = [p for n, p in named_params
                        if p.requires_grad and any(nd in n for nd in no_decay)]
        groups = []
        if len(params_decay) > 0:
            groups.append({"params": params_decay, "weight_decay": wd, "lr": lr})
        if len(params_nodec) > 0:
            groups.append({"params": params_nodec, "weight_decay": 0.0, "lr": lr})
        return groups

    optimizer_grouped_parameters = []
    # RoBERTa（文本编码器）
    optimizer_grouped_parameters += build_groups(param_roberta,
                                                 config.fin_tuning_lr,
                                                 config.weight_decay_rate)
    # 下游模块
    optimizer_grouped_parameters += build_groups(param_downstream,
                                                 config.downs_en_lr,
                                                 config.weight_decay_rate)
    # CLIP视觉塔（仅在 --vision_trainable 时加入优化器）
    if getattr(config, "vision_trainable", False):
        optimizer_grouped_parameters += build_groups(param_clip,
                                                     config.clip_lr,
                                                     config.weight_decay_rate)

    # ---- 去重校验（防止任何参数出现在多个组）----
    seen = set()
    for gi, g in enumerate(optimizer_grouped_parameters):
        for p in g["params"]:
            pid = id(p)
            if pid in seen:
                raise ValueError("parameter appears in multiple groups (group index {0})".format(gi))
            seen.add(pid)

    # （可选）打印快照，方便确认分组是否合理
    def count_params(named_params):
        return sum(p.numel() for _, p in named_params)

    print("\n[DEBUG] param grouping snapshot")
    print(" - roberta  tensors:", len(param_roberta), " params:", count_params(param_roberta))
    print(" - clip     tensors:", len(param_clip), " params:", count_params(param_clip),
          " (vision_trainable=", getattr(config, "vision_trainable", False), ")")
    print(" - downstream tensors:", len(param_downstream), " params:", count_params(param_downstream))
    print()

    # optimizer = torch.optim.AdamW(optimizer_grouped_parameters)

    optimizer = torch.optim.AdamW(optimizer_grouped_parameters)
    t_total = len(train_loader) // config.gradient_accumulation_steps * config.epochs
    warmup_steps = int(t_total * config.warmup_prop)
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=warmup_steps, num_training_steps=t_total)

    best_f1 = 0.0
    patience_counter = 0

    # =============== 加载 checkpoint（模型权重 / 或完整状态） ===============
    if config.continue_train_name != "None":
        load_dir = ckpt_dir
        model.load_state_dict(torch.load(os.path.join(load_dir, "model.pt")))
        optimizer.load_state_dict(torch.load(os.path.join(load_dir, "optimizer.pt")))
        scheduler.load_state_dict(torch.load(os.path.join(load_dir, "scheduler.pt")))

        with open(os.path.join(load_dir, "training_state.json")) as f:
            state = json.load(f)
        start_epoch = state["epoch"]
        best_f1 = state["best_f1"]

    global_step = 0
    try:
        for epoch in range(start_epoch, config.epochs + 1):
            model.train()
            total_loss = 0.0

            loop = tqdm(train_loader, desc="Epoch {0}/{1}".format(epoch, config.epochs), ncols=100)
            for step, batch in enumerate(loop):

            # input_ids = batch[0].to(device, non_blocking=True)
            # # token_type_ids = batch[1].to(device, non_blocking=True)
            # attention_mask = batch[1].to(device, non_blocking=True)
            # labels = batch[2].to(device, non_blocking=True)
            # image_tensor = batch[3].to(device, non_blocking=True)
                input_ids = batch["input_ids"].to(device)
                attention_mask = batch["attention_mask"].to(device)
                labels = batch["labels"].to(device)
                images = batch.get("image", None)
                if images is not None:
                    images = images.to(device)

                loss = model(
                    input_ids,
                    attention_mask,
                    image_tensor=images,
                    labels=labels,
                )

                loss = loss / config.gradient_accumulation_steps
                loss.backward()

            # 每个 step 的 gradient norm 和 learning rate 记录（在 optimizer.step 之前）
                if (step + 1) % config.gradient_accumulation_steps == 0:
                    # 计算 grad_norm
                    total_norm = 0.0
                    for p in model.parameters():
                        if p.grad is not None:
                            param_norm = p.grad.data.norm(2)
                            total_norm += param_norm.item() ** 2
                    total_norm = total_norm ** 0.5

                    #  clip 梯度，优化器步进
                    torch.nn.utils.clip_grad_norm_(model.parameters(), config.clip_grad)
                    optimizer.step()
                    scheduler.step()
                    optimizer.zero_grad()

                    current_lr = scheduler.get_last_lr()[0]
                    writer.add_scalar("train/grad_norm", total_norm, global_step)
                    writer.add_scalar("train/learning_rate", current_lr, global_step)
                    global_step += 1

                total_loss += loss.item()
                loop.set_postfix(loss="{0:.4f}".format(loss.item()), lr=optimizer.param_groups[0]['lr'])

            avg_loss = total_loss / len(train_loader)
            writer.add_scalar("train/loss", avg_loss, epoch)
            print("\n✅ Epoch {0} Train Loss: {1:.4f}".format(epoch, avg_loss))

        # f1, report = evaluate(model, val_loader, device, train_dataset.id2label)
            acc, f1, p, r = evaluate_model(model, val_loader, device, train_dataset.label_mapping)
            print(
                "🎯Epoch {0} Eval F1: {1:.4f} precision: {2:.4f} recall: {3:.4f} acc:{4:.4f}".format(epoch, f1, p, r, acc))
            writer.add_scalar("eval/f1", f1, epoch)
            writer.add_scalar("eval/precision", p, epoch)
            writer.add_scalar("eval/recall", r, epoch)
            writer.add_scalar("eval/acc", acc, epoch)

        # Early Stop
            if f1 > best_f1 + config.patience:
                best_f1 = f1
                patience_counter = 0
                save_model_checkpoint(model, optimizer, scheduler, config, save_dir, epoch, best_f1)
                print("✅ Model saved to {0}".format(save_dir))
            else:
                patience_counter += 1
                print("📉 No improvement, patience {0}/{1}".format(patience_counter, config.patience_num))
                if epoch >= config.min_epoch_num and patience_counter >= config.patience_num:
                    print("⛔️ Early stopping triggered.")
                    break
    finally:
        writer.close()


if __name__ == "__main__":
    from config import get_config

    set_seed(42)
    config = get_config()
    train(config)
